### ISSUE TITLE
[Repo] .gitignore

### ISSUE THREAD

**Issue by konne** [r-hannuschka/ngx-responsivemenu#39]
why you include this .vscode setting? (git.ignore....)

**Comment by r-hannuschka** [comment]
good question, i think this comes with one of this github plugins for visual studio code i never implemented this. Maybe we should put .vscode settings file into gitignore

**Comment by r-hannuschka** [comment]
So i watch again this is nothing special ( this is my github plugin for visual studio code)

```json
{
    "git.ignoreLimitWarning": true
}
```
means (as description me says):

> Ignores the warning when there are too many changes in a repository.
> This setting cannot be applied now. It will be applied when you open this folder directly.

I think we can close this now :)
